version:  '3.8'
services:
  mysql:
    image: mariadb:11.2
    container_name: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php8
    restart: on-failure
    user: ${LOCAL_USER_UID}
    depends_on:
      - redis

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx-alpine
    restart: on-failure
    depends_on:
      - php

  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    restart: on-failure
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}