version:  '3.8'
services:
  mysql:
    image: mysql:8.2
    container_name: mysql-db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: db_user_root_pass
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_DATABASE: app_db
      #MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer-app
    restart: on-failure
    ports:
      - '3001:8080'

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000:9000'
    container_name: php8
    volumes:
      - './app/:/var/www/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx-alpine
    restart: on-failure
    volumes:
      - './app/public:/var/www/app/public'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '3000:80'
      - '444:443'
    depends_on:
      - php

    # Switch to debug mode:
    #command: [ nginx-debug, '-g', 'dlemon off;' ]

volumes:
  dbdata: