# override compose.yaml file with dev requirements
services:
  mysql:
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:3306'

  adminer:
    image: adminer
    container_name: adminer-app
    restart: on-failure
    ports:
      - '${ADMINER_PORT}:8080'

  php:
    volumes:
      - './app/:/var/www/app'
    ports:
      - '${PHP_PORT}:9000'

  nginx:
    volumes:
      - './app/public:/var/www/app/public'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
      - '${NGINX_SSL_PORT}:443'

    # Switch to debug mode:
    # command: [ nginx-debug, '-g', 'dlemon off;' ]

  redis:
    volumes:
      - cache:/data
    ports:
      - '${REDIS_PORT}:6379'

    # save data every 20 seconds if at least 1 key changed
    # Double dollars, so that the variable is not expanded by Docker Compose
    # Surround by quotes, so that the shell does not split the password
    command:
      - /bin/sh
      - -c
      - redis-server --save 20 1 --loglevel warning --requirepass "$${REDIS_PASSWORD}"

volumes:
  dbdata:
  cache:
    driver: local